name: flutterquiz
description: A new Flutter application.
publish_to: "none"
version: 1.0.17+21

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  apple_sign_in_safety: ^0.0.6
  assets_audio_player: ^3.0.6
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.0
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.3
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_html: ^3.0.0-alpha.1
  flutter_local_notifications: ^14.0.0+2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.0
  google_fonts: ^4.0.4
  google_mobile_ads: ^2.4.0
  google_sign_in: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.0.0
  image_cropper: ^5.0.0
  image_picker: ^0.8.7+5
  in_app_purchase: ^3.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  ios_insecure_screen_detector: ^0.0.2
  just_audio: ^0.9.33
  launch_review: ^3.0.1
  lottie: ^2.3.2
  octo_image: ^1.0.0+1
  unity_ads_plugin: ^0.3.8
  package_info_plus: ^3.1.2
  path_provider: ^2.0.15
  pin_code_fields: ^7.4.0
  scratcher: ^2.3.0
  screenshot: ^2.1.0
  share_plus: ^6.3.4
  shared_preferences: ^2.1.1
  sms_autofill: ^2.3.0
  url_launcher: ^6.1.11
  wakelock: ^0.6.2
  webview_flutter: ^3.0.4
  country_code_picker: ^3.0.0
  flutter_windowmanager: ^0.2.0
  flutter_widget_from_html: ^0.9.1
  encrypt:
  flutter_tex: ^4.0.3+4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0
  dart_code_metrics_presets: ^2.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  flutter_launcher_icons: ^0.13.1
  intl: ^0.17.0
  http: ^0.13.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter:
  uses-material-design: true

  assets:
    #    - assets/google_fonts/
    - assets/images/
    - assets/images/profile/

    - assets/images/emojis/
    - assets/images/coins/

    - assets/languages/
    - assets/animations/

    - assets/sounds/
    - assets/files/
